"""Initial migration with new learning_footpaths POSTGRESQL database

Revision ID: 758642a04c0c
Revises: 
Create Date: 2024-11-21 13:44:03.458638

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "758642a04c0c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.VARCHAR(length=32), primary_key=True, unique=True, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=345), unique=True, nullable=False),
        sa.Column("password", sa.TEXT(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
