"""Fix grade level column name

Revision ID: a21e45cf7543
Revises: e5ab38cd395f
Create Date: 2025-02-02 00:38:43.132611

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a21e45cf7543"
down_revision = "e5ab38cd395f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the old foreign key constraint
    op.drop_constraint(
        "exhibition_grade_levels_grade_level_id_fkey",
        "exhibition_grade_levels",
        type_="foreignkey",
    )

    # Rename the column
    op.alter_column(
        "exhibition_grade_levels",
        "grade_level_id",
        new_column_name="grade_level",
        existing_type=sa.String(2),
    )

    # Add the new foreign key constraint
    op.create_foreign_key(
        "exhibition_grade_levels_grade_level_fkey",
        "exhibition_grade_levels",
        "grade_levels",
        ["grade_level"],
        ["grade"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new foreign key constraint
    op.drop_constraint(
        "exhibition_grade_levels_grade_level_fkey",
        "exhibition_grade_levels",
        type_="foreignkey",
    )

    # Rename the column back
    op.alter_column(
        "exhibition_grade_levels",
        "grade_level",
        new_column_name="grade_level_id",
        existing_type=sa.String(2),
    )

    # Recreate the old foreign key constraint
    op.create_foreign_key(
        "exhibition_grade_levels_grade_level_id_fkey",
        "exhibition_grade_levels",
        "grade_levels",
        ["grade_level_id"],
        ["grade"],
    )
    # ### end Alembic commands ###
