"""remove user_badge_progress

Revision ID: [autogenerated_id]
Revises: add_badge_completion_tracking
Create Date: [autogenerated_date]

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "[autogenerated_id]"
down_revision = "add_badge_completion_tracking"
branch_labels = None
depends_on = None


def upgrade():
    # Drop indexes first
    op.drop_index("ix_user_badge_progress_badge_id", table_name="user_badge_progress")
    op.drop_index("ix_user_badge_progress_user_id", table_name="user_badge_progress")

    # Drop the table
    op.drop_table("user_badge_progress")


def downgrade():
    # Recreate the table
    op.create_table(
        "user_badge_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(32), nullable=False),
        sa.Column("badge_id", sa.Integer(), nullable=False),
        sa.Column("is_discovered", sa.Boolean(), nullable=False, default=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False, default=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["badge_id"], ["custom_badges.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge_progress"),
    )

    # Recreate indexes
    op.create_index(
        "ix_user_badge_progress_user_id", "user_badge_progress", ["user_id"]
    )
    op.create_index(
        "ix_user_badge_progress_badge_id", "user_badge_progress", ["badge_id"]
    )
