"""Add grade level associations in the database

Revision ID: e5ab38cd395f
Revises: 3a5814adf2d6
Create Date: 2025-01-21 19:47:46.332355

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e5ab38cd395f"
down_revision = "3a5814adf2d6"
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('questions')
#     op.drop_table('exhibitions')
#     op.drop_table('user_exhibition_progress')
#     op.drop_table('learning_footpaths')
#     op.drop_table('footpath_exhibition')
#     op.drop_table('users')
#     op.drop_table('temp_quiz_results')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('temp_quiz_results',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('session_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('footpath_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('footpath_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='temp_quiz_results_exhibition_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='temp_quiz_results_pkey'),
#     sa.UniqueConstraint('session_id', name='temp_quiz_results_session_id_key')
#     )
#     op.create_table('users',
#     sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(length=345), autoincrement=False, nullable=False),
#     sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('grade_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='users_pkey'),
#     sa.UniqueConstraint('email', name='users_email_key'),
#     postgresql_ignore_search_path=False
#     )
#     op.create_table('footpath_exhibition',
#     sa.Column('footpath_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='footpath_exhibition_exhibition_id_fkey'),
#     sa.ForeignKeyConstraint(['footpath_id'], ['learning_footpaths.id'], name='footpath_exhibition_footpath_id_fkey'),
#     sa.PrimaryKeyConstraint('footpath_id', 'exhibition_id', name='footpath_exhibition_pkey')
#     )
#     op.create_table('learning_footpaths',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('big_question', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='learning_footpaths_pkey'),
#     sa.UniqueConstraint('name', name='learning_footpaths_name_key')
#     )
#     op.create_table('user_exhibition_progress',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('footpath_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='user_exhibition_progress_exhibition_id_fkey'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_exhibition_progress_user_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='user_exhibition_progress_pkey')
#     )
#     op.create_table('exhibitions',
#     sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exhibitions_id_seq'::regclass)"), autoincrement=True, nullable=False),
#     sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('big_question', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='exhibitions_pkey'),
#     postgresql_ignore_search_path=False
#     )
#     op.create_table('questions',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='questions_exhibition_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='questions_pkey')
#     )
#     # ### end Alembic commands ###


def upgrade():
    # Create grade_levels table
    op.create_table(
        "grade_levels",
        sa.Column("grade", sa.String(2), primary_key=True),
        sa.Column("description", sa.String(50), nullable=True),
    )

    # Create exhibition_grade_levels association table
    op.create_table(
        "exhibition_grade_levels",
        sa.Column("exhibition_id", sa.Integer(), nullable=False),
        sa.Column("grade_level", sa.String(2), nullable=False),
        sa.ForeignKeyConstraint(
            ["exhibition_id"],
            ["exhibitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grade_level"],
            ["grade_levels.grade"],
        ),
        sa.PrimaryKeyConstraint("exhibition_id", "grade_level"),
    )

    # Add grade_level column to questions table
    op.add_column("questions", sa.Column("grade_level", sa.String(2), nullable=True))

    # Add foreign key constraint for questions.grade_level
    op.create_foreign_key(
        "fk_questions_grade_level",
        "questions",
        "grade_levels",
        ["grade_level"],
        ["grade"],
    )

    # Modify user.grade_level to be String(2)
    op.alter_column(
        "users",
        "grade_level",
        existing_type=sa.String(20),
        type_=sa.String(2),
        existing_nullable=True,
    )

    # Insert default grade levels
    op.execute(
        """
        INSERT INTO grade_levels (grade, description) VALUES
        ('K', 'Kindergarten'),
        ('1', 'Grade 1'),
        ('2', 'Grade 2'),
        ('3', 'Grade 3'),
        ('4', 'Grade 4'),
        ('5', 'Grade 5'),
        ('6', 'Grade 6'),
        ('7', 'Grade 7'),
        ('8', 'Grade 8'),
        ('9', 'Grade 9'),
        ('10', 'Grade 10'),
        ('11', 'Grade 11'),
        ('12', 'Grade 12')
    """
    )


def downgrade():
    # Remove foreign key constraint from questions
    op.drop_constraint("fk_questions_grade_level", "questions", type_="foreignkey")

    # Drop grade_level column from questions
    op.drop_column("questions", "grade_level")

    # Drop the association table
    op.drop_table("exhibition_grade_levels")

    # Drop the grade_levels table
    op.drop_table("grade_levels")

    # Revert user.grade_level to String(20)
    op.alter_column(
        "users",
        "grade_level",
        existing_type=sa.String(2),
        type_=sa.String(20),
        existing_nullable=True,
    )
