"""Add user exhibition progress table

Revision ID: ee2c8795b54a
Revises: 
Create Date: 2024-12-08 12:53:35.547449

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee2c8795b54a"
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('learning_footpaths')
#     op.drop_table('exhibitions')
#     op.drop_table('footpath_exhibition')
#     op.drop_table('users')
#     op.drop_table('questions')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('questions',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='questions_exhibition_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='questions_pkey')
#     )
#     op.create_table('users',
#     sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(length=345), autoincrement=False, nullable=False),
#     sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='users_pkey'),
#     sa.UniqueConstraint('email', name='users_email_key')
#     )
#     op.create_table('footpath_exhibition',
#     sa.Column('footpath_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('exhibition_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name='footpath_exhibition_exhibition_id_fkey'),
#     sa.ForeignKeyConstraint(['footpath_id'], ['learning_footpaths.id'], name='footpath_exhibition_footpath_id_fkey'),
#     sa.PrimaryKeyConstraint('footpath_id', 'exhibition_id', name='footpath_exhibition_pkey')
#     )
#     op.create_table('exhibitions',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('big_question', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='exhibitions_pkey')
#     )
#     op.create_table('learning_footpaths',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('big_question', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='learning_footpaths_pkey'),
#     sa.UniqueConstraint('name', name='learning_footpaths_name_key')
#     )
#     # ### end Alembic commands ###
def upgrade():
    # Add new user_exhibition_progress table
    op.create_table(
        "user_exhibition_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(32), nullable=True),
        sa.Column("exhibition_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True, default=0),
        sa.Column("completed", sa.Boolean(), nullable=True, default=False),
        sa.ForeignKeyConstraint(
            ["exhibition_id"],
            ["exhibitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # Remove only the new table
    op.drop_table("user_exhibition_progress")
